### ISSUE TITLE
Verify tests for DC

### ISSUE THREAD

**Issue by armfazh** [cloudflare/go#62] opened 2021-03-10 21:50 UTC
Tests for DCs fail when running isolated, but they pass when invoked as a batch (i.e. `go test -v -run=.`)

### What did you do?
```sh
$ cd src/crypto/tls
$ ../../../bin/go test -v -run=DC
```

### What did you expect to see?

```
=== RUN   TestDCHandshakeServerAuth
--- PASS: TestDCHandshakeServerAuth (0.14s)
=== RUN   TestDCHandshakeClientAuth
--- PASS: TestDCHandshakeClientAuth (0.14s)
=== RUN   TestDCHandshakeClientAndServerAuth
--- PASS: TestDCHandshakeClientAndServerAuth (0.03s)

```

### What did you see instead?
```
    delegated_credentials_test.go:592: test #1 dcCounter:1, (tls13: DC server and client support) fails: x509: certificate signed by unknown authority
    delegated_credentials_test.go:598: test #1 (tls13: DC server and client support) usedDC = false; expected true
    delegated_credentials_test.go:592: test #1 dcCounter:2, (tls13: DC server and client support) fails: x509: certificate signed by unknown authority
    delegated_credentials_test.go:598: test #1 (tls13: DC server and client support) usedDC = false; expected true
    delegated_credentials_test.go:592: test #1 dcCounter:3, (tls13: DC server and client support) fails: x509: certificate signed by unknown authority
    delegated_credentials_test.go:598: test #1 (tls13: DC server and client support) usedDC = false; expected true

```

**Comment by claucece** [comment] 2021-03-11 01:48
Yes, I see. I'm not really sure why is only flagged in this case of testing but I can take a look at this next week. 

The problem is that we are providing a mock of a certificate (without the correct root and chain and all), as it is only for testing.

We can provide that whole chain, though it might be too much for testing. Or just set the `c.config.InsecureSkipVerify` to true, as it is often on testing, which will invalidate the check (as it fails on `verifyServerCertificate`).

**Comment by claucece** [comment] 2021-03-15 14:48
I added a PR @armfazh ;) Let me know your thoughts.

**Comment by claucece** [comment] 2021-03-15 22:38
Merged now.

**Closed as completed by claucece** 2021-03-15 22:38 UTC
Labels: question, pqxp
